name: "Hello World Workflow"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        
      - name: "Print Hello World 2"
        run: echo "Hello World"
